CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requestor_id INT REFERENCES users (id),
    created      TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    is_available BOOL DEFAULT FALSE,
    owner_id     INT REFERENCES users (id),
    request_id   INT REFERENCES requests (id),
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    INT REFERENCES items (id),
    booker_id  INT REFERENCES users (id),
    status     VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

create table if not exists comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(255)                            not null,
    item_id   INT REFERENCES items (id),
    author_id INT REFERENCES users (id),
    created   TIMESTAMP WITHOUT TIME ZONE             not null,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);
