create table if not exists USERS
(
    id    bigint primary key generated by default as identity not null,
    name  varchar(255)                                        not null,
    email varchar(512)                                        not null,
    unique (email)
);

create table if not exists REQUESTS
(
    id           bigint primary key generated by default as identity not null,
    description  varchar(512)                                        ,
    requestor_id int references USERS (id),
    created      timestamp without time zone
);

create table if not exists ITEMS
(
    id           bigint primary key generated by default as identity not null,
    name         varchar(255)                                        not null,
    description  varchar(255)                                        not null,
    is_available bool default false,
    owner_id     int references USERS (id),
    request_id   int references REQUESTS (id)
);

create table if not exists BOOKINGS
(
    id         bigint primary key generated by default as identity not null,
    start_date timestamp without time zone,
    end_date   timestamp without time zone,
    item_id    int references ITEMS (id),
    booker_id  int references USERS (id),
    status     varchar(10)                                         not null
);

create table if not exists COMMENTS
(
    id        bigint primary key generated by default as identity not null,
    text      varchar(255)                                        not null,
    item_id   int references ITEMS (id),
    author_id int references USERS (id),
    created   timestamp without time zone                         not null
);